In [ ]:

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

train_df = pd.read_csv("train_clean.csv")
test_df = pd.read_csv("test_clean.csv")

y_train = train_df["label"]
y_test = test_df["label"]

print("Train size:", train_df.shape)
print("Test size:", test_df.shape)
print(train_df["filtered_text"][0][:200])

Train size: (25000, 3)
Test size: (25000, 3)
rented curiousyellow video store controversy surrounded first released also heard first seized us customs ever tried enter country therefore fan films considered controversial really see myselfthe plo


In [3]:
#Bag of words
import time
cv=CountVectorizer(max_features=5000)
start=time.time()
X_train_cv=cv.fit_transform(train_df["filtered_text"])
X_test_cv=cv.transform(test_df["filtered_text"])
end=time.time()
print("Count Vectorization done")
print("Train matrix shape: ",X_train_cv.shape)
print("Test matrix shape: ",X_test_cv.shape)
print(f"Time taken: {end-start:.2f} seconds")


Count Vectorization done
Train matrix shape:  (25000, 5000)
Test matrix shape:  (25000, 5000)
Time taken: 4.76 seconds


In [5]:
print(X_train_cv[:5, :10].toarray())


[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=5000)
start=time.time();
X_train_tfidf=tfidf.fit_transform(train_df["filtered_text"])
X_test_tfidf=tfidf.transform(test_df["filtered_text"])
end=time.time();
print("Train matrix shape",X_train_tfidf.shape)
print("Test matrix shape", X_test_tfidf.shape)
print(f"Time taken: {end-start:.2f} seconds")

Train matrix shape (25000, 5000)
Test matrix shape (25000, 5000)
Time taken: 6.17 seconds


In [7]:
import gensim.downloader as api
glove_model=api.load("glove-wiki-gigaword-100")
print("Done")          

Done


In [8]:
def review_to_vector(review,model,vector_size=100):
    words=review.split()
    vectors=[model[word] for word in words if word in model]
    if len(vectors)==0:
        return np.zeros(vector_size)
    return np.mean(vectors, axis=0)
start=time.time()
X_train_glove=np.array([review_to_vector(review,glove_model) for review in train_df["filtered_text"]])
X_test_glove=np.array([review_to_vector(review,glove_model) for review in test_df["filtered_text"]])
end=time.time();
print("Train matrix shape: ",X_train_glove.shape)
print("Test matrix shape: ",X_test_glove.shape)
print(f"Time taken: {end-start:.2f} seconds")

Train matrix shape:  (25000, 100)
Test matrix shape:  (25000, 100)
Time taken: 9.26 seconds


In [9]:
np.save("X_train_glove.npy", X_train_glove)
np.save("X_test_glove.npy", X_test_glove)

In [10]:
from scipy import sparse
sparse.save_npz("X_train_cv.npz", X_train_cv)
sparse.save_npz("X_test_cv.npz", X_test_cv)

In [11]:
sparse.save_npz("X_train_tfidf.npz", X_train_tfidf)
sparse.save_npz("X_test_tfidf.npz", X_test_tfidf)


In [12]:
y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)
